config/routes.rb
Rails.application.routes.draw do

  get "up" => "rails/health#show", as: :rails_health_check

  root "pages#home"

  get "questions" => "pages#questions"
  get "win" => "pages#win"
  get "game_over" => "pages#game_over"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
end

app/models/game.rb
class Game < ApplicationRecord
end

app/models/question.rb
class Question < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def questions
    @questions = Question.all
    # @game = Game.last
  end

  def game_over
  end

  def win
    @friends = Friend.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RodrickThese</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.jsdelivr.net/npm/@tsparticles/confetti@3.0.3/tsparticles.confetti.bundle.min.js"></script>
  </head>

  <body>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/game_over.html.erb
<section class="h-dvh flex flex-col justify-center items-center">

  <div class="flex flex-col justify-center items-center gap-8 px-8">

    <p class="neon-text rotating-text text-center" data-text="GAME OVER">GAME OVER</p>

    <%= image_tag 'yamcha.jpg', alt:"", class:"" %>

    <%= link_to 'Retenter le quizz', questions_path, class: 'p-4 bg-[#99CE0B] text-xl' %>
  </div>

</section>


<style>
/* * {border: 1px red solid} */
</style>

app/views/pages/home.html.erb
<section data-controller="music" class="h-dvh flex flex-col justify-between items-center relative overflow-hidden bg-home">
  <%= link_to win_path do %>
    <div class="w-20 h-24 absolute top-0 right-0"></div>
  <% end %>
  <div class="flex flex-col h-full justify-around items-center px-8 text-center ">
    <!-- <h1 class="text-bold text-3xl">Docteur Rodrick Gibert</h1> -->

    <div class="bg-black p-4 bg-opacity-90">
      <div class="flex flex-col justify-center relative ">
        <h1 class="gold-text" data-text="Docteur Rodrick Gilbert">
          <span class="gold-text__highlight" data-text="Docteur Rodrick Gilbert">Docteur Rodrick Gilbert</span>
        </h1>
      </div>
    </div>

    <%= image_tag 'audrick_portrait.png', alt: '', class: 'w-28 h-auto audrick-head-static drop-shadow-xl' %>

    <button data-action="click->music#playMusic" class="p-4 bg-[#099F55] flex flex-row items-center gap-2 confettis-btn rounded-3xl drop-shadow-xl">
      <svg class="w-6 text-white fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M499.1 6.3c8.1 6 12.9 15.6 12.9 25.7l0 72 0 264c0 44.2-43 80-96 80s-96-35.8-96-80s43-80 96-80c11.2 0 22 1.6 32 4.6L448 147 192 223.8 192 432c0 44.2-43 80-96 80s-96-35.8-96-80s43-80 96-80c11.2 0 22 1.6 32 4.6L128 200l0-72c0-14.1 9.3-26.6 22.8-30.7l320-96c9.7-2.9 20.2-1.1 28.3 5z"/></svg>
      <p class="text-base text-white">Mets la musique !</p>
    </button>

    <div class="flex flex-col gap-4 justify-center items-center bg-black p-4 bg-opacity-90">
      <h2 class="text-white text-base">Félicitations, tu as enfin fini ta thèse!</h2>
      <p class="text-white text-base">Mais il te reste encore l'épreuve finale pour prétendre à ton diplôme!</p>
      <p class="text-white text-base">Réponds à toutes les questions du COUIZE pour découvrir la surprise</p>
      <p class="text-white text-base">Mais attention, tu ne disposes que de 3 vies!</p>
    </div>
    <%= link_to questions_path, class:"flex flex-row items-center gap-2 bg-[#099F55] p-4 drop-shadow-xl" do %>
      <svg class="w-6 text-white fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512"><!--!Font Awesome Free 6.6.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M192 0c-41.8 0-77.4 26.7-90.5 64L64 64C28.7 64 0 92.7 0 128L0 448c0 35.3 28.7 64 64 64l256 0c35.3 0 64-28.7 64-64l0-320c0-35.3-28.7-64-64-64l-37.5 0C269.4 26.7 233.8 0 192 0zm0 64a32 32 0 1 1 0 64 32 32 0 1 1 0-64zM105.8 229.3c7.9-22.3 29.1-37.3 52.8-37.3l58.3 0c34.9 0 63.1 28.3 63.1 63.1c0 22.6-12.1 43.5-31.7 54.8L216 328.4c-.2 13-10.9 23.6-24 23.6c-13.3 0-24-10.7-24-24l0-13.5c0-8.6 4.6-16.5 12.1-20.8l44.3-25.4c4.7-2.7 7.6-7.7 7.6-13.1c0-8.4-6.8-15.1-15.1-15.1l-58.3 0c-3.4 0-6.4 2.1-7.5 5.3l-.4 1.2c-4.4 12.5-18.2 19-30.6 14.6s-19-18.2-14.6-30.6l.4-1.2zM160 416a32 32 0 1 1 64 0 32 32 0 1 1 -64 0z"/></svg>
      <p class="text-base text-white">Commencer le COUIZE</p>
    <% end %>
    </div>

  </div>
  <%= image_tag 'luffy.webp', alt: 'Commencer le couize', class: 'w-full h-auto' %>
  <%= image_tag 'audrick_portrait.png', alt: '', class: 'audrick-head-dynamic' %>
  <%= image_tag 'loic_perrin.png', alt: '', class: 'loic-dynamic' %>
  <%= image_tag 'trotinette.png', alt: '', class: 'loic-dynamic-right' %>

</section>

<style>
/* * {border: 1px red solid} */
</style>

<script>
  const fireBtn = document.querySelector(".confettis-btn");

fireBtn.addEventListener("click", () => {
  const end = Date.now() + 6 * 1000;

// go Buckeyes!
const colors = ["#bb0000", "#ffffff"];

(function frame() {
  confetti({
    particleCount: 2,
    angle: 60,
    spread: 55,
    origin: { x: 0 },
    colors: colors,
  });

  confetti({
    particleCount: 2,
    angle: 120,
    spread: 55,
    origin: { x: 1 },
    colors: colors,
  });

  if (Date.now() < end) {
    requestAnimationFrame(frame);
  }
})();
});
</script>

app/views/pages/questions.html.erb
<section class="h-dvh flex flex-col justify-center items-center bg-questions">

  <div data-controller="questions" class="flex flex-col justify-center items-center gap-4 px-8 relative">
    <div class="flex flex-row items-center justify-center">
      <p class="neon-text rotating-text" data-text="COUIZE">COUIZE</p>
    </div>
    <div class="flex flex-row items-center justify-center gap-2">
      <div data-action="click->questions#playMusic" class="p-4 bg-[#3AFF3A] rounded-full drop-shadow-xl flex justify-center items-center">
        <svg class="" fill="currentColor" height="26" viewBox="0 0 16 16" width="26" xmlns="http://www.w3.org/2000/svg"><path d="M9 13c0 1.105-1.12 2-2.5 2S4 14.105 4 13s1.12-2 2.5-2 2.5.895 2.5 2z"/><path d="M9 3v10H8V3h1z" fill-rule="evenodd"/><path d="M8 2.82a1 1 0 0 1 .804-.98l3-.6A1 1 0 0 1 13 2.22V4L8 5V2.82z"/></svg>
      </div>
      <p class="text-[#08FF08] p-4 bg-black bg-opacity-80 text-xl" data-questions-target="lives">Nombre de vies: 3</p>
    </div>

    <ul class="text-white flex flex-col justify-center items-center text-center">
      <% @questions.each_with_index do |question, index| %>
        <li data-questions-target="question" class="<%= 'hidden' if index > 0 %> p-4 bg-black bg-opacity-80">
          <p class="mb-8 p-4 bg-black bg-opacity-80 text-xl">Question N°<%= question.number %>/<%= (@questions.all.length - 1) %></p>
          <h4 class="text-xl pb-4"><%= simple_format(question.question) %></h4>
          <ul>
            <% question.answers.each do |answer| %>
              <li class="py-2">
                <label class="text-base">
                  <input data-questions-target="radioChoice" class="mr-2" type="radio" name="question<%= question.number %>" value="<%= answer %>"/><%= answer %>
                </label>
              </li>
            <% end %>
          </ul>
          <button data-action="click->questions#checkAnswer" data-correct-answer="<%= question.answer %>" class="p-4 bg-[#099F55] text-white text-xl mt-4">Valider!</button>
        </li>
        <% end %>
    </ul>
    <%= image_tag 'good_answer.png', alt: '', class: 'good-answer', data: { questions_target: 'goodAnswer' } %>
    <%= image_tag 'middle_finger.png', alt: '', class: 'good-answer', data: { questions_target: 'badAnswer' } %>
  </div>

</section>

<style>
/* * {border: 1px red solid} */
</style>

app/views/pages/quizz.html.erb
<ul data-controller="questions">
  <p data-questions-target="lives">Nombre de vies: 3</p>
  <br>
  <% @questions.each_with_index do |question, index| %>
    <li data-questions-target="question" class="<%= 'hidden' if index > 0 %>">
      <p>Question N°<%= question.number %>/<%= @questions.all.length %></p>
      <h4><%= question.question %></h4>
      <ul>
        <% question.answers.each do |answer| %>
          <li>
            <label>
              <input data-questions-target="radioChoice" type="radio" name="question<%= question.number %>" value="<%= answer %>"/><%= answer %>
            </label>
          </li>
        <% end %>
      </ul>
      <button data-action="click->questions#checkAnswer"  data-correct-answer="<%= question.answer %>" class="p-4 bg-[#3AFF3A]">Valider!</button>
    </li>
    <% end %>
</ul>

app/views/pages/win.html.erb
<section data-controller="siu" class="flex flex-col justify-between items-center">
  <div class="h-svh justify-around flex flex-col items-center text-center gap-12 bg-win px-8">
    <!-- <h1>GG EASY NOOB!</h1> -->
    <div class="text-wrapper mt-8">
      <h1 class="text-6xl gg drop-shadow-2xl stroke-black">BRAVO
        <span class="text-5xl noob stroke-black">DOCTEUR G.!</span>
      </h1>
      <h1 class="text-6xl gg drop-shadow-2xl">BRAVO
        <span class="text-5xl noob">DOCTEUR G.!</span>
      </h1>
    </div>

    <%= image_tag 'echarpe_asse.png', alt:'', class:'scarf-anim drop-shadow-xl'%>

    <button data-action="click->siu#unMute" class="p-4 bg-[#3AFF3A] mt-4 flex flex-row items-center gap-2 confettis-btn rounded-3xl text-xl drop-shadow-xl">
      <svg class="w-6" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M499.1 6.3c8.1 6 12.9 15.6 12.9 25.7l0 72 0 264c0 44.2-43 80-96 80s-96-35.8-96-80s43-80 96-80c11.2 0 22 1.6 32 4.6L448 147 192 223.8 192 432c0 44.2-43 80-96 80s-96-35.8-96-80s43-80 96-80c11.2 0 22 1.6 32 4.6L128 200l0-72c0-14.1 9.3-26.6 22.8-30.7l320-96c9.7-2.9 20.2-1.1 28.3 5z"/></svg>
      Mets le son !
    </button>

    <div class="text-white flex flex-row items-center justify-center gap-1 mb-8 p-4 bg-black bg-opacity-50">
      <svg class="text-white fill-current w-16 h-16 bouncing-arrow drop-shadow-xl" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><!--!Font Awesome Free 6.6.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M256 0a256 256 0 1 0 0 512A256 256 0 1 0 256 0zM244.7 395.3l-112-112c-4.6-4.6-5.9-11.5-3.5-17.4s8.3-9.9 14.8-9.9l64 0 0-96c0-17.7 14.3-32 32-32l32 0c17.7 0 32 14.3 32 32l0 96 64 0c6.5 0 12.3 3.9 14.8 9.9s1.1 12.9-3.5 17.4l-112 112c-6.2 6.2-16.4 6.2-22.6 0z"/></svg>
      <p class="text-xl">Scrolle pour voir la vidéo et les messages!</p>
      <svg class="text-white fill-current w-16 h-16 bouncing-arrow drop-shadow-xl" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><!--!Font Awesome Free 6.6.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M256 0a256 256 0 1 0 0 512A256 256 0 1 0 256 0zM244.7 395.3l-112-112c-4.6-4.6-5.9-11.5-3.5-17.4s8.3-9.9 14.8-9.9l64 0 0-96c0-17.7 14.3-32 32-32l32 0c17.7 0 32 14.3 32 32l0 96 64 0c6.5 0 12.3 3.9 14.8 9.9s1.1 12.9-3.5 17.4l-112 112c-6.2 6.2-16.4 6.2-22.6 0z"/></svg>
    </div>
  </div>

  <%= video_tag 'Audrick_these_V2.mp4', id: 'audrickVideo', autoplay: false, muted: true, controls: true, class: 'video' %>

  <div class="flex flex-col items-center text-center gap-8 mt-8">

    <div class="text-white flex flex-row px-8 items-center justify-center gap-1">
      <svg class="text-white fill-current w-16 h-16 bouncing-arrow drop-shadow-xl" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><!--!Font Awesome Free 6.6.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M256 0a256 256 0 1 0 0 512A256 256 0 1 0 256 0zM244.7 395.3l-112-112c-4.6-4.6-5.9-11.5-3.5-17.4s8.3-9.9 14.8-9.9l64 0 0-96c0-17.7 14.3-32 32-32l32 0c17.7 0 32 14.3 32 32l0 96 64 0c6.5 0 12.3 3.9 14.8 9.9s1.1 12.9-3.5 17.4l-112 112c-6.2 6.2-16.4 6.2-22.6 0z"/></svg>
      <p class="text-xl">Clique sur les bouilles des gens (ce n'est pas une contrepétrie) pour découvrir leurs messages!</p>
      <svg class="text-white fill-current w-16 h-16 bouncing-arrow drop-shadow-xl" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><!--!Font Awesome Free 6.6.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M256 0a256 256 0 1 0 0 512A256 256 0 1 0 256 0zM244.7 395.3l-112-112c-4.6-4.6-5.9-11.5-3.5-17.4s8.3-9.9 14.8-9.9l64 0 0-96c0-17.7 14.3-32 32-32l32 0c17.7 0 32 14.3 32 32l0 96 64 0c6.5 0 12.3 3.9 14.8 9.9s1.1 12.9-3.5 17.4l-112 112c-6.2 6.2-16.4 6.2-22.6 0z"/></svg>
    </div>

    <% @friends.each_with_index do |friend, index| %>
      <div class="flex text-white relative px-8">
        <div data-controller="toggle" class="flex flex-col gap-4">
          <div class="flex w-full <%= index.even? ? 'justify-start' : 'justify-end' %>">
            <div class="peeps drop-shadow-xl flex-shrink-0 <%= index.even? ? 'peeps-anim' : 'peeps-anim-reverse' %>">
              <%= image_tag friend.avatar, alt: "", class: "w-24 h-auto mt-4 rounded-full cursor-pointer", data: { action: "click->toggle#fire" } %>
              <% if index.even? %>
                <%= image_tag 'luffy_chapeau.png', alt: "", class: "w-24 h-auto absolute -top-2 rotate-12 left-3" %>
              <% else %>
                <%= image_tag 'luffy_chapeau.png', alt: "", class: "w-24 h-auto absolute -top-2 rotate-12 -right-3" %>
              <% end %>
            </div>
          </div>

          <div data-toggle-target="togglableElement" class="w-full smooth-toggle togglable-element text-center">
            <p class="text-2xl font-bold <%= index.even? ? 'text-left' : 'text-right' %> "><%= friend.name %>:</p>
            <p class="shadow-2xl text-xl text-left bg-[#FFC510] text-black p-4 rounded-xl"><%= friend.message %></p>
          </div>
        </div>
      </div>
    <% end %>

    <div class="text-white flex flex-row px-8 items-center justify-center gap-1">
      <svg class="text-white fill-current w-12 h-12 bouncing-arrow drop-shadow-xl" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><!--!Font Awesome Free 6.6.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M256 0a256 256 0 1 0 0 512A256 256 0 1 0 256 0zM244.7 395.3l-112-112c-4.6-4.6-5.9-11.5-3.5-17.4s8.3-9.9 14.8-9.9l64 0 0-96c0-17.7 14.3-32 32-32l32 0c17.7 0 32 14.3 32 32l0 96 64 0c6.5 0 12.3 3.9 14.8 9.9s1.1 12.9-3.5 17.4l-112 112c-6.2 6.2-16.4 6.2-22.6 0z"/></svg>
      <p class="text-xl">Scrolle encore un peu!</p>
      <svg class="text-white fill-current w-12 h-12 bouncing-arrow drop-shadow-xl" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><!--!Font Awesome Free 6.6.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M256 0a256 256 0 1 0 0 512A256 256 0 1 0 256 0zM244.7 395.3l-112-112c-4.6-4.6-5.9-11.5-3.5-17.4s8.3-9.9 14.8-9.9l64 0 0-96c0-17.7 14.3-32 32-32l32 0c17.7 0 32 14.3 32 32l0 96 64 0c6.5 0 12.3 3.9 14.8 9.9s1.1 12.9-3.5 17.4l-112 112c-6.2 6.2-16.4 6.2-22.6 0z"/></svg>
    </div>

    <div data-controller="dick" class="flex flex-col gap-4">
      <p data-action="click->dick#fire" class="mx-auto text-black text-bold text-2xl p-4 bg-[#3AFF3A] mt-4 drop-shadow-xl">Dernière surprise, clique ici! </p>
      <div data-dick-target="togglableElement" class="w-full smooth-toggle togglable-element">
        <%= image_tag 'penis.png', alt:'', class:'drop-shadow-2xl mb-8 dick-anim origin-top-right px-8 ' %>
      </div>
    </div>
  </div>
  <!-- <%= image_tag 'trotinette.png', alt: '', class: 'loic-dynamic' %>
  <%= image_tag 'trotinette.png', alt: '', class: 'loic-dynamic-right' %> -->
</section>


<style>
.smooth-toggle {
  transition: opacity 0.5s ease, visibility 0.5s ease;
}

.togglable-element {
  overflow: hidden;
  transition: height 0.3s ease;
  height: 0;
}

.togglable-element.expanded {
  height: auto; /* This will be dynamically set by JavaScript */
}

/* * {border: 1px red solid} */
</style>

<script>
  document.addEventListener('DOMContentLoaded', () => {
    const peepsElements = document.querySelectorAll('.peeps');

    peepsElements.forEach(peeps => {
      peeps.addEventListener('click', () => {
        peeps.classList.toggle('active');
      });
    });
  });

  const fireBtn = document.querySelector(".confettis-btn");

  fireBtn.addEventListener("click", () => {
    const duration = 30 * 1000,
      animationEnd = Date.now() + duration,
      defaults = { startVelocity: 20, spread: 100, ticks: 15, zIndex: 0 };

    function randomInRange(min, max) {
      return Math.random() * (max - min) + min;
    }

    const interval = setInterval(function () {
      const timeLeft = animationEnd - Date.now();

      if (timeLeft <= 0) {
        return clearInterval(interval);
      }

      const particleCount = 20 * (timeLeft / duration);

      confetti(
        Object.assign({}, defaults, {
          particleCount,
          origin: { x: randomInRange(0.1, 0.3), y: Math.random() - 0.2 },
        })
      );
      confetti(
        Object.assign({}, defaults, {
          particleCount,
          origin: { x: randomInRange(0.5, 0.7), y: Math.random() - 0.2 },
        })
      );
    }, 250);
  });
</script>